### ISSUE TITLE
TS.4.a: Prototype predicate translation service - continuous integration

### ISSUE THREAD

**Issue by mmersmann** [TranslatorIIPrototypes/EdgeNormalization#3]
Related:
[TS.4: Prototype predicate translation service](https://github.com/TranslatorIIPrototypes/EdgeNormalization/issues/2)
[TS.4.b: Prototype predicate translation service - documentation](https://github.com/TranslatorIIPrototypes/EdgeNormalization/issues/4)

**Comment by cbizon** [comment]
Unit tests covering edge resolution and ubergraph queries successfully running in travis-ci
